### ISSUE TITLE
Stránka ke stažení je poměrně složitá

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/download-page#16]
Přemýšlel jsem, jestli nezjednodušit [stránku ke stažení](https://www.linux-mint-czech.cz/ke-stazeni/) do podoby více jako https://www.ubuntu.cz/ziskat-ubuntu/stahnout-desktop/ nebo https://www.mozilla.cz/stahnout/.

Dneska hodně prostoru zabírají hashe, ale návod na jejich použití je stejně jinde (a asi ho nechceme duplikovat). Naopak tlačítka, která by měla být jasnou výzvou ke stažení jsou dost malá a tak trochu stranou.

Taky nevím, jestli chceme nabízet i starší verze Mintu. IMO primárně by měli všichni pro nové instalace stahovat nejnovější verzi. Pokud vědomě chtějí starší, najdou ji na https://linuxmint.com/download_all.php, kam můžeme odkázat.

**Comment by MikkCZ** [comment]
Co myslíš @sgflt ?

**Comment by sgflt** [comment]
Souhlasím s tvým návrhem. Stahování pak bude přehlednější.

**Comment by MikkCZ** [comment]
Jak se ti to (ne)líbí teď? https://www.linux-mint-czech.cz/ke-stazeni/

**Comment by MikkCZ** [comment]
@sgflt Jak se ti to (ne)líbí teď? https://www.linux-mint-czech.cz/ke-stazeni/

**Comment by sgflt** [comment]
Nevypustíme i 32bit obrazy? Jinak to vypadá OK.

**Comment by MikkCZ** [comment]
Teď lepší? :)

**Comment by sgflt** [comment]
Takto to už vypadá dostatečně jednoduše.
