### ISSUE TITLE
Data pro plugin jsou uložená v kořeni instalace WordPressu

### ISSUE THREAD

**Issue by MikkCZ** [linux-mint-czech/download-page#8]
Toto není úplně ideální, protože plugin závisí na souboru v konkrétním umístění úplně mimo.

@sgflt nevadilo by ti, kdybych přesunul to XMLko z rootu instalace do adresáře s pluginem? Případně mohu nastavit automatický deploy tak, že kdykoliv pushneš úpravu xmlka tady na GitHubu, projeví se to i na webu. Ve výsledku tak budeš moci XMLko upravovat přes rozhraní Githubu i když zrovna nebudeš mít přístup na SFTP.

**Comment by MikkCZ** [comment]
Byl by to takový mezistupeň před vyřešením #2.

**Comment by sgflt** [comment]
Vůbec by mi to nevadilo. Push do gitu se mi celkem zamlouvá.

**Comment by MikkCZ** [comment]
@sgflt Hotovo. XMLko je v gitu a automatický deploy nastavený. Po pushnutí je to do pár vteřin nahrané na webu. Samozřejmě jsem ti přidal sem do repozitáře práva k zápisu.
